# Generated by Django 4.0.4 on 2022-12-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_questionmodel_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='help_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
