# Generated by Django 4.0.4 on 2022-12-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionmodel_help_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='help_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
