# Generated by Django 4.0.4 on 2022-11-17 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0002_contentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_content', to='space.contentmodel')),
                ('space', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='space.spacemodel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_content', to='space.contentmodel')),
            ],
        ),
    ]
