# Generated by Django 4.0.4 on 2022-11-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_relationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationmodel',
            old_name='source',
            new_name='source_content',
        ),
        migrations.RenameField(
            model_name='relationmodel',
            old_name='target',
            new_name='target_content',
        ),
    ]
