# Generated by Django 4.0.4 on 2022-11-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_rename_source_relationmodel_source_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
